version: '3.8'

services:
  app:
    build: .
    container_name: nabshop-app
    ports:
      - "3000:3000"  # پورت مربوط به سرور
    volumes:
      - .:/app  # اشتراک‌گذاری پوشه پروژه از ماشین میزبان با کانتینر
    environment:
      - NODE_ENV=development
    working_dir: /app  # دایرکتوری کاری داخل کانتینر
    command: npm run dev  # دستور اجرای سرور با npm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge